# -*- coding: utf-8 -*-
"""data_argumentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lupe8i96AV5O3SE1qM6xZNFy-HGJolbD
"""

!unzip fruit.zip # zip the files you want to operate

!pip install Augmentor # install the library

import Augmentor

p = Augmentor.Pipeline('/content/fruit' ) # where the file is

p.rotate(probability=0.7, max_left_rotation=10, max_right_rotation=10)

p.zoom(probability=0.3, min_factor=0.5, max_factor=1)
p.flip_left_right(probability=0.4)
p.flip_top_bottom(probability=0.8)
p.skew(probability=0.5)
p.shear(probability=0.5, max_shear_left=0.5, max_shear_right=0.5)
p.random_distortion(probability=0.5, magnitude=1, grid_width=1, grid_height=1)

p.sample(10)  # how many sample do you want

! zip -r /content/fruit1.zip /content/fruit/  # zip up the finished files and get ready to download